 
 <div id="main" class="container-fluid">
  
  <h3 class="page-header">Pesquisa</h3>
  
  <form action="visualizar" name="form_empresa" method="post">
  	<div class="row">
  	  <div class="form-group col-md-4">
  	  	<label for="input">Pesquisar empresa por CNPJ:</label>
  	  	<input type="text" name="cnpj" class="form-control" id="p2" placeholder="Digite aqui.">
  	  </div>
	</div>
	
	<div class="row">
	  <div class="col-md-12">
	  	<button type="submit" class="btn btn-primary">Pesquisar</button>
	  </div>
	</div>
  </form>
  
  <hr />
  
 </div>
