 
 <div id="main" class="container-fluid">
  
  <h3 class="page-header">Adicionar Sócio</h3>
  
  <form name="adicionar_socio" action="" method="post">
  	
        <div class="row">
  	  <div class="form-group col-md-4">
  	  	<label for="input">Nome</label>
  	  	<input type="text" name="nome" class="form-control" id="exampleInputEmail1" placeholder="Digite aqui.">
  	  </div>
	  <div class="form-group col-md-4">
  	  	<label for="input2">CPF</label>
  	  	<input type="text" name="cpf" class="form-control" id="exampleInputEmail1" placeholder="Digite aqui.">
  	  </div>
	  <div class="form-group col-md-4">
  	  	<label for="input3">E-mail</label>
  	  	<input type="text" name="email" class="form-control" id="exampleInputEmail1" placeholder="Digite aqui.">
  	  </div>
	</div>
      
        <div class="row">
  	  <div class="form-group col-md-8">
  	  	<label for="sel1">Empresa</label>
                <select class="form-control" name="empresa" id="sel1">
                  <?php
                    if ($this->empresas) {
                        foreach ($this->empresas as $obj) {
                            echo '<option value="'.$obj->Id.'">'.$obj->NomeEmpresa.'</option>';
                        }
                    }
                  ?>
                </select>
  	  </div>
	</div>
		
	<hr />
	
	<div class="row">
	  <div class="col-md-12">
	  	<button type="submit" class="btn btn-primary">Salvar</button>
		<a href="index" class="btn btn-default">Cancelar</a>
	  </div>
	</div>

  </form>
 </div>