
 <div id="main" class="container-fluid">
  
  <h3 class="page-header">Dados do sócio</h3>
  
  <div class="row">
      
    <div class="col-md-4">
      <p><strong>Nome</strong></p>
  	  <p><?php echo $this->nome; ?></p>
    </div>
	
    <div class="col-md-4">
      <p><strong>CPF</strong></p>
  	  <p><?php echo $this->cpf; ?></p>
    </div>
      
    <div class="col-md-4">
      <p><strong>E-mail</strong></p>
  	  <p><?php echo $this->email; ?></p>
    </div>

  </div>
 
  <hr />
  
  <h4>Empresas que tem participação</h4>
  
  <div class="row">
      
    <div class="col-md-4">
      <p><strong>Nome</strong></p>
    </div>
	
    <div class="col-md-4">
      <p><strong>CNPJ</strong></p>
    </div>

  </div>
  
  <?php
    if ($this->empresas) {
        foreach ($this->empresas as $objeto) {
            echo '<div class="row">

                    <div class="col-md-4">
                          <p>'.$objeto->NomeEmpresa.'</p>
                    </div>

                    <div class="col-md-4">
                          <p>'.$objeto->CNPJ.'</p>
                    </div>

                  </div>';
        }
    }
  ?>	
  
 <hr />
 
 </div>

