<!DOCTYPE html>
<html lang="pt-br">
<head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>Gerenciador de Sócios</title>

 <link href="../public/css/bootstrap.min.css" rel="stylesheet">
 <link href="../public/css/style.css" rel="stylesheet">
</head>
<body>
    
 <?php
    try {
        $read = Zend_Auth::getInstance()->getStorage()->read(); 
        $usuario_logado = $read->Nome;
        if (empty($usuario_logado)) {
            echo "Necessário efetuar o login para acessar o sistema!!";
            exit();
        }
    }
    catch (Zend_Db_Exception $e) {
        echo $e->getMessage();
    } 
 ?>

 <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
   <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
     <span class="sr-only">Toggle navigation</span>
     <span class="icon-bar"></span>
     <span class="icon-bar"></span>
     <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="">Gerenciador de Sócios</a>
    <span class="navbar-brand"> - </span>
    <a class="navbar-brand" href="../socio/index">Sócios</a>
    <a class="navbar-brand" href="../empresa/index">Empresas</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
     <li><a href=""><?php echo $usuario_logado; ?></a></li>
     <li><a href="../index/sair">Sair</a></li>
    </ul>
   </div>
  </div>
 </nav>

<?php echo $this->layout()->content; ?>

 <script src="../public/js/jquery.min.js"></script>
 <script src="../public/js/bootstrap.min.js"></script>
 <script src="../public/js/main.js"></script>
</body>
</html>